### PR TITLE
Feature/dockerize

### PR DESCRIPTION
**Pull request by nabidam**
for now you can run **namizun** using docker with these little changes, but for certain it should be refactored so the core could be easily debugged and developed.

### CODE REVIEW

**Comment by malkemit** [comment]
why docker?

**Comment by nabidam** [comment]
> why docker?

why not? easy maintenance, isolated environment, can be run on any platform and etc...

**Comment by malkemit** [comment]
I don't understand, why should it be run in an isolated environment?

**Comment by malkemit** [comment]
By the way, the code you wrote for Dockerization has some problems

Both in installation and execution

**Comment by nabidam** [comment]
The most important reason is that you can install the project on any distribution, and it's implementation would be ez.
btw I think you don't like docker at all or even you don't know the concepts of containers. If you want to know, I recommend that you can read [this](https://stackoverflow.com/questions/62250381/why-dockerize-a-service-or-application-when-you-could-install-it) or search it.

After all I thank you for your time and dedication to FOSS community <3

**Comment by malkemit** [comment]
For some reason I don't want to be installed on any distribution.

**Pull request closed without merging**
